### PR TITLE
Resolve #60

### LINKED ISSUE #60: Off by one when wrapping InputStream
image

I use `ProgressBar.wrap(InputStream, ProgressBarBuilder)` where the stream is created by `URL.openStream()`. I set the initial max to the actual file size. Reducing the max by one (or even 10) has zero effect and will still show the actual file size (as if I set it to the correct size).

### PR DESCRIPTION
**Pull request by mordechaim**

### CODE REVIEW

**Comment by ctongfei** [comment]
Thanks a lot @mordechaim !

**Comment by ctongfei** [comment]
It is now published as version `0.8.1`.

**Comment by mordechaim** [comment]
Thanks @ctongfei for this beautiful project

**Comment by ctongfei** [comment]
You are welcome!

**Pull request merged**
