### PR TITLE
Vehovsky multiline progressbar

### PR DESCRIPTION
**Pull request by ctongfei**

### CODE REVIEW

**Comment by mikehearn** [comment]
Fantastic! I love this library, have used it before, and I was just looking for this feature. Great work all. Any idea when it might get released?

**Comment by ctongfei** [comment]
@vehovsky `CARRIAGE_RETURN` is the designated name in the ASCII standard for this particular control character.

**Comment by ctongfei** [comment]
@mikehearn It will be released in around a week (without the children progress bar feature). Thanks for the patience as I am very busy right now.

**Comment by mikehearn** [comment]
No hurry. Thanks for your work!

**Pull request merged**
