### PR TITLE
added getCurrent; last refresh at stop

### PR DESCRIPTION
**Pull request by rualpe**
dear Tongfei,
thanks again for this fantastic piece of useful work.

I'm using it in a multithreaded setup, and would like to know the progress, so I'm suggesting to add a getter of current value (does not seem to be super-secret).

Alsodiscovered that on stop we do not have that last update we used to have in 0.4.x version.
So suggesting to add one more refresh after stop.

### CODE REVIEW

**Comment by rualpe** [comment]
wow! thanks, dear Tongfei.
I hope people would be glad to see your nice little project evolve.

**Comment by ctongfei** [comment]
Thanks, glad you like it! I'll release a version 0.5.1 in the coming weekend that incorporates your pull request with some minor modifications.

**Comment by ctongfei** [comment]
I added a bunch of getters (getTask, getMessage, getCurrent, getMax) and fixed the last update problem.
Please bump the version number to 0.5.1.

**Comment by rualpe** [comment]
Super. thanks!

**Comment by rualpe** [comment]
works fine!
`Retrying those that failed 100% │████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████│ 8974535/8974535 (0:06:33 / 0:00:00) 
`

**Pull request merged**
